ALTER TABLE msr.instrument_daily_data_model
    DROP COLUMN "Country",
    DROP COLUMN "AssetClass",
    DROP COLUMN "Currency",
    DROP COLUMN "RIC";

ALTER TABLE msr.instrument_daily_data_model
    ADD "QuoteId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE msr.instrument_daily_data_model
    ALTER COLUMN "QuoteId" DROP IDENTITY;

ALTER TABLE msr.instrument_daily_data_model
    DROP CONSTRAINT instrument_daily_data_model_pkey;

ALTER TABLE msr.instrument_daily_data_model
    ADD CONSTRAINT instrument_daily_data_model_pk
        PRIMARY KEY ("QuoteId", "Tape", "Date", "TC", "Venue");